### ISSUE TITLE
Header Image for Project list page

### ISSUE THREAD

**Issue by racheljcox** [themejack/pine#1]
Sorry this isn't really an issue but I don't know how else to reach you.

Is there a customization option for adding a header image like in the demo? When I removed the name of the projects list page, I was left with a HUGE blank space between the site name and the project list. Is this how it's supposed to look? I can't find any options for a banner image.

Or do I need to create a child's theme to make these changes?

Thanks

Rachel

**Comment by anteprimorac** [comment]
Hi @racheljcox,
this is a good place to reach us, also all WordPress.org themes have support forum. For Pine you can find it here - https://wordpress.org/support/theme/pine.

You can define featured image on all pages(including Project list page template) and posts to add header image.

> When I removed the name of the projects list page, I was left with a HUGE blank space between the site name and the project list. Is this how it's supposed to look?

This is a issue. We will fix it in next release.

**Comment by racheljcox** [comment]
The featured image on the demo site's main page is a lot taller than the other featured image headers.... I assumed this was customized just for the demo? Please let me know.

**Comment by anteprimorac** [comment]
That happens because on front(main) page the content is also displayed bellow of page title. Featured image is resized depending on content and title size.

**Comment by racheljcox** [comment]
So how would I get a big main image like in the demo? I would insert an
image into the portfolio posts page?

Thanks,
Rachel

On Fri, Apr 22, 2016 at 9:54 AM, Ante Primorac notifications@github.com
wrote:

> That happens because on front(main) page the content is also displayed
> bellow of page title. Featured image is resized depending on content and
> title size.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/themejack/pine/issues/1#issuecomment-213438557

## 

Rachel J. Cox
www.racheljcox.com
240. 462. 0745

**Comment by anteprimorac** [comment]
You can define featured image and add blank new lines into page content. Something like this - http://demo.slicejack.com/pine/test-page/.

Screenshot from admin panel:
![test-page-admin](https://cloud.githubusercontent.com/assets/972083/14744028/19534694-08a5-11e6-9525-d415515abf41.png)

**Comment by racheljcox** [comment]
Thank you so much! It works. Think I have it figured out.

R

On Fri, Apr 22, 2016 at 10:13 AM, Ante Primorac notifications@github.com
wrote:

> You can define featured image and add blank new lines into page content.
> Something like this - http://demo.slicejack.com/pine/test-page/.
> 
> Screenshot from admin panel:
> [image: test-page-admin]
> https://cloud.githubusercontent.com/assets/972083/14744028/19534694-08a5-11e6-9525-d415515abf41.png
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/themejack/pine/issues/1#issuecomment-213443986

## 

Rachel J. Cox
www.racheljcox.com
240. 462. 0745
