### ISSUE TITLE
Images in Projects appearing right aligned

### ISSUE THREAD

**Issue by racheljcox** [themejack/pine#2]
No matter what size or alignment I select for the media I insert in a projects post, the image always appears with more spacing on the left than the right. In the demo they do not appear this way. It seems fine on small device sizes but not at full width desktop screen. I can fix this in the CSS but I want to make sure there isn't some option in the wp admin that I am missing.

My earlier issue- regarding the banner image- I resolved by adding a featured image to the portfolio posts page. I assume that was what I was supposed to do?

THANK YOU!

**Comment by racheljcox** [comment]
Ack nevermind!

**Comment by anteprimorac** [comment]
Hi @racheljcox, do you have online link where we can see what is happening with project images?

**Comment by racheljcox** [comment]
This was my mistake... in the customizer under global formatting I accidentally had it set with a left sidebar.
