### ISSUE TITLE
Issue with protofolio..

### ISSUE THREAD

**Issue by rssjdesign** [themejack/pine#4]
Hi guys i installed your theme and it isn't showing the portfolio menu in the admin panel. 

also also you have a demo content file? pls thanks

**Comment by anteprimorac** [comment]
Hi @rssjdesign, sorry for late response. To get portfolio menu in the admin panel you need to install Jetpack plugin and activate Custom Content Types, you can get more information about it here - https://jetpack.com/support/custom-content-types/.

We currently don't have a demo content file, but we are working on bringing it.

**Comment by 4rzael** [comment]
Hi @anteprimorac !
Any updates on a possible demo content file ?

**Comment by aziev** [comment]
@anteprimorac @4rzael any news about demo content?

**Comment by alenvuletic** [comment]
Hi @4rzael and @aziev, unfortunately we stopped working on and supporting this theme.

Sorry for bad news :(

**Comment by aziev** [comment]
@alenvuletic ok, no problems
