### ISSUE TITLE
social buttons are gone.. ?

### ISSUE THREAD

**Issue by rafugee** [themejack/pine#7]
Hi

Thanks for really great theme. There is one issue that I am having and that is with the footer and social buttons. After I added my links all the buttons disappeared? Is there a glitch in the code, or what do you recommend to fix this matter. Thanks 

PS. I also copied function.php from this site, and the buttons remain gone?

**Comment by anteprimorac** [comment]
Hi @rafugee,
please try to reinstall theme from WordPress.org - https://wordpress.org/themes/pine/. If the problem still occurs, let me know.

**Comment by rafugee** [comment]
Hi @anteprimorac,
thanks for our advice. I re-installed theme and the problem is still there. The social media buttons were viewable initially, but once I updated links from # to actual hyperlinks they disappeared?
What do you recommend now?

**Comment by anteprimorac** [comment]
Hi @rafugee,
sorry for inconvenience, we are going to fix this in next release.

**Comment by soniamoretti** [comment]
Hi, I'm having the same problem with the social media icons.
in the meantime I installed a SocialMedia PlugIn --> Ultimate Social Media PLUS

If anyone got to fix this, thank you :)
