### ISSUE TITLE
h1 color with different bg-image

### ISSUE THREAD

**Issue by Ferym26** [themejack/pine#8]
how it work?
http://oplines.com/portfolio/app-1/
im use #000 png bg image but h1 color still dark

**Comment by anteprimorac** [comment]
Hi @Ferym26,
try to turn off Jetpack Photon. The problem with Jetpack Photon that it doesn't have support for CORS. Let me know if that resolves your problem.

**Comment by Ferym26** [comment]
without Jetpack doesnt work portfolio. wtf

http://slicejack.com/pine-free-wordpress-portfolio-theme/
"In order to use this feature within Jetpack you must enable Custom Content Types modules and then enable Portfolio post type."

i use Jetpack by WordPress.com Version 4.3.2

**Comment by anteprimorac** [comment]
Hi @Ferym26,
instructions to activate Portfolio post type are here - https://jetpack.com/support/custom-content-types/#portfolios

**Comment by Ferym26** [comment]
so? when I turn Jetpack off with him and Portfolio.
and how can I do these different grids? http://joxi.ru/12MeDqduWLvZ2J http://joxi.ru/BA06pPZTR4gymy etc. 
thx

**Comment by anteprimorac** [comment]
Hi @Ferym26,
I'm not sure if I understand your questions. If you turn off Jetpack then Portfolio won't work. That "grids" on your screenshot are galleries. You can find instructions here https://jetpack.com/support/tiled-galleries/.

As far as I can see most off your issues are related to Jetpack. Sorry but we can not provide support for Jetpack.
